# First steps with Python
This will guide you through the very first steps with Pyhon. It is a very brief introduction. You will have to google search for more details and explanations. I decided to write it in english because you will have to use english anyway when looking up tutorials etc.

You can edit the code in the cells and then run it with **Ctrl+Enter**. You should run the cells one by one because latter cells may use the variables created in earlier cells.


## printing and strings
Look at this code and try to undestand. Try to modify parameters and watch what happens.

In [1]:
# comment by using hash
print('Hello world!')
s = 'whatever'
print(s)
print('\n') #newline
print(s+' '+s) # concatenate strings
print(s[2:-2]) #from second to last but one
print(s[s.find('a'):]) # from position where 'a' is find up to the end

Hello world!
whatever


whatever whatever
atev
atever


## Variables and numbers

In [2]:
import numpy as np #numerical library is imported. Functions within library can be called by using np prefix
m = 2.5
c = 2.99e8
E = m*c**2
print('energy is '+str(E)+' J')
print('energy is {:.2} J'.format(E))
g = 9.8
h = 30
v = np.sqrt(2*g*h)
print('speed: ',v)
# division of numbers
print(m/2)
# note that variables in python do not have any specific type. You can assign a string e.g. to variable m that was previously a number
m = 'foobar'



energy is 2.235025e+17 J
energy is 2.2e+17 J
speed:  24.24871130596428
1.25


### Exercise 1
Complete the code that calculates kinetic energy of a running man and print the answer in a neat way.

In [13]:
m = 80 #kg
v = 9.2 #m/s
# define variable E that will hold the result of the calculation of kinetic energy
# Print the results as a whole phrase such as 'Kinetics energy is 100 J'.

## Working with lists and arrays

In [3]:
#Let's first clear the namespace (existing variables etc.)
%reset -f
#Let's import numerical library again
import numpy as np
# Let's define a list of numbers
lst = [1,4,9,16,25]
print('list:')
print(lst)
# access element with index 1. Note that indexing starts from 0
print(lst[1])
# access last item of the list
print(lst[-1])
# access a sub-list
print(lst[2:4])
# You can add an item at the end of the list
lst.append(36)
print(lst)


list:
[1, 4, 9, 16, 25]
4
25
[9, 16]
[1, 4, 9, 16, 25, 36]


In [24]:
# For numerical manipulations, you can convert the list to a numpy array
a = np.array(lst)
print('numpy array:')
print(a)
# You can make almost any numerical manipulation with the array a and replace the values in the array with the new ones
print('array after mathematical operation:')
a = np.sqrt(a)-1
print(a)
# You can also create numpy array directly
a = np.array([2,4,6,8,10])
print(a)
# To access the items of the array, you can again use [index] notation
print('access items')
print(10*a[0])
print(a[2:4]/5)

numpy array:
[ 1  4  9 16 25 36]
[0. 1. 2. 3. 4. 5.]
[ 2  4  6  8 10]
access items
20
[1.2 1.6]


### Exercise 2
Make a numpy array called p that will contain numbers from 1 to five. Then create array r by calculating square root of array p. Finally, print the array r.

In [ ]:
# p = ...
# r = ...
# print = ...

## Ranges

In [4]:
# You do not have to define a sequence of numbers manually. For evenly spaced array of numbers, you can do
a = np.arange(3,20,2)
print(a)
# or
print(np.linspace(0,1000,5))

[ 3  5  7  9 11 13 15 17 19]
[   0.  250.  500.  750. 1000.]


## For loop interation
You can iterate over the items of an array or a list

In [31]:
array = np.arange(1,5)
# for loop is one of the most basic statements
for number in array:
    print('cubic of ' + str(number) + ' is ',str(number**3))
    
    

cubic of 1 is  1
cubic of 2 is  8
cubic of 3 is  27
cubic of 4 is  64


In [32]:
# You do not have to define an array. You can use a simple iterator
for k in range(5):
    print('Two to {} is {}'.format(k,2**k))

Two to 0 is 1
Two to 1 is 2
Two to 2 is 4
Two to 3 is 8
Two to 4 is 16


### Exercise 3
Define an array x that will contain only odd numbers between 0 and 100. Then use the for cycle to sum these numbers.

In [34]:
#array = ...
suma = 0
#for ...
    # suma = suma + ...
print(suma)

0


## Numpy methods for calculations on arrays
However, it is often very ineffective to use for loops to do some calculations on arrays, because numpy array is an object which has many useful methods defined. Look at several examples:

In [41]:
v = np.arange(0,11) # note that when the second number is 11, it means that the last number will be 10, because it is the greates integer smaller than 11.
print(v)
print(v.sum())
print(v.mean())
print(v.max())
# Also it is often non-sensical to use a for loop to do some simple numerical manipulation with the numpy array. You can do
result = v**3
result = 2**v
print(result)

55
5.0
10
[   1    2    4    8   16   32   64  128  256  512 1024]


### Exercise 4
Repeat exercise 3, but without using a For cycle. Define an array x that will contain only odd numbers between 0 and 100. Then use numpy array method to calculate the sum and print the result. 

In [ ]:
# your code here

## If statement
Conditions are the absolute basic of any program. The syntax in python is

In [59]:
for i in range(10):
    if (i>3) and (i<=7):
        print(i)
    elif i==8:
        print('This is magical 8!')
    else:
        print('not recognised!')

not recognised!
not recognised!
not recognised!
not recognised!
4
5
6
7
This is magical 8!
not recognised!


### Exercise 5
Write a code that evaluates whether numbers in the list are odd or even, printing either 'odd' or 'even' for each number. The reminder after division is calculated using operator modulo (%), for example 7%3 equals 1. Remember that to check whether two experssion are equal, you have to use a double equal sign == (for example x==5 evaluates to True if x equals 5). Writing x=5 assigns the value 5 to the variable x and cannot be used to check the condition.

In [60]:
numbers = [23,16,2,71,56,40]
# Here comes for statement
# Here comes the if/else statement